"""
End-to-end integration test: exercises all 6 Python analysis agents
against a realistic diff payload, then verifies the combined output
is suitable for the TypeScript assessor.
"""

import json
import sys
from pathlib import Path

# Add all agent packages to sys.path so we can import without pip install
AGENTS_DIR = Path(__file__).resolve().parent.parent.parent / "agents"
for agent_dir in ["framework", "security", "ip-license", "dependency", "ai-detector", "quality", "policy"]:
    src = AGENTS_DIR / agent_dir
    if src.exists():
        sys.path.insert(0, str(src))

from sentinel_agents.types import DiffEvent, DiffFile, DiffHunk, ScanConfig

# Import all 6 agents
from sentinel_security.agent import SecurityAgent
from sentinel_license.agent import LicenseAgent
from sentinel_dependency.agent import DependencyAgent
from sentinel_aidetector.agent import AIDetectorAgent
from sentinel_quality.agent import QualityAgent
from sentinel_policy.agent import PolicyAgent


def build_realistic_payload() -> DiffEvent:
    """Build a realistic diff event that triggers findings across all agents."""
    return DiffEvent(
        scan_id="e2e-scan-001",
        project_id="proj-sentinel-test",
        commit_hash="abc123def456",
        branch="feature/user-auth",
        author="dev@example.com",
        timestamp="2026-03-09T12:00:00Z",
        files=[
            # File 1: Security issues (SQL injection, hardcoded secret)
            DiffFile(
                path="src/api/users.py",
                language="python",
                hunks=[
                    DiffHunk(
                        old_start=10,
                        old_count=5,
                        new_start=10,
                        new_count=15,
                        content=(
                            '+import os\n'
                            '+import sqlite3\n'
                            '+\n'
                            '+API_KEY = "sk-1234567890abcdef"\n'
                            '+\n'
                            '+def get_user(user_id):\n'
                            '+    conn = sqlite3.connect("db.sqlite")\n'
                            '+    query = f"SELECT * FROM users WHERE id = {user_id}"\n'
                            '+    return conn.execute(query).fetchone()\n'
                            '+\n'
                            '+def authenticate(token):\n'
                            '+    return eval(token)\n'
                        ),
                    )
                ],
                ai_score=0.0,
            ),
            # File 2: AI-generated code with tool markers
            DiffFile(
                path="src/utils/helpers.ts",
                language="typescript",
                hunks=[
                    DiffHunk(
                        old_start=1,
                        old_count=0,
                        new_start=1,
                        new_count=20,
                        content=(
                            '+// Generated by GitHub Copilot\n'
                            '+export function calculateDistance(lat1: number, lon1: number, lat2: number, lon2: number): number {\n'
                            '+  const R = 6371;\n'
                            '+  const dLat = toRad(lat2 - lat1);\n'
                            '+  const dLon = toRad(lon2 - lon1);\n'
                            '+  const a = Math.sin(dLat / 2) * Math.sin(dLat / 2) +\n'
                            '+    Math.cos(toRad(lat1)) * Math.cos(toRad(lat2)) *\n'
                            '+    Math.sin(dLon / 2) * Math.sin(dLon / 2);\n'
                            '+  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));\n'
                            '+  return R * c;\n'
                            '+}\n'
                            '+\n'
                            '+function toRad(deg: number): number {\n'
                            '+  return deg * (Math.PI / 180);\n'
                            '+}\n'
                            '+\n'
                            '+export function formatCurrency(amount: number): string {\n'
                            '+  return `$${amount.toFixed(2)}`;\n'
                            '+}\n'
                        ),
                    )
                ],
                ai_score=0.85,
            ),
            # File 3: Quality issues (high complexity, duplication)
            DiffFile(
                path="src/services/processor.py",
                language="python",
                hunks=[
                    DiffHunk(
                        old_start=1,
                        old_count=0,
                        new_start=1,
                        new_count=30,
                        content=(
                            '+def process_data(data, mode, flag1, flag2, flag3):\n'
                            '+    if mode == "a":\n'
                            '+        if flag1:\n'
                            '+            if flag2:\n'
                            '+                if flag3:\n'
                            '+                    return data * 2\n'
                            '+                else:\n'
                            '+                    return data * 3\n'
                            '+            else:\n'
                            '+                if flag3:\n'
                            '+                    return data + 1\n'
                            '+                else:\n'
                            '+                    return data - 1\n'
                            '+        else:\n'
                            '+            return data\n'
                            '+    elif mode == "b":\n'
                            '+        if flag1:\n'
                            '+            if flag2:\n'
                            '+                if flag3:\n'
                            '+                    return data * 4\n'
                            '+                else:\n'
                            '+                    return data * 5\n'
                            '+            else:\n'
                            '+                return data\n'
                            '+        else:\n'
                            '+            return data\n'
                            '+    else:\n'
                            '+        return None\n'
                        ),
                    )
                ],
                ai_score=0.0,
            ),
            # File 4: License/dependency issues
            DiffFile(
                path="package.json",
                language="json",
                hunks=[
                    DiffHunk(
                        old_start=5,
                        old_count=3,
                        new_start=5,
                        new_count=6,
                        content=(
                            '+  "dependencies": {\n'
                            '+    "lodash": "^4.17.21",\n'
                            '+    "express": "^4.18.0",\n'
                            '+    "unknown-pkg-xyz": "1.0.0"\n'
                            '+  }\n'
                        ),
                    )
                ],
                ai_score=0.0,
            ),
        ],
        scan_config=ScanConfig(
            security_level="strict",
            license_policy="copyleft-block",
            quality_threshold=0.7,
        ),
    )


def run_all_agents(event: DiffEvent) -> list[dict]:
    """Run all 6 agents and return their FindingEvent dicts."""
    agents = [
        SecurityAgent(),
        LicenseAgent(),
        DependencyAgent(),
        AIDetectorAgent(),
        QualityAgent(),
        PolicyAgent(),
    ]

    results = []
    for agent in agents:
        finding_event = agent.run_scan(event)
        result_dict = finding_event.to_dict()
        results.append(result_dict)
        print(f"  {agent.name:20s} -> {finding_event.status:10s} | "
              f"{len(finding_event.findings)} findings | "
              f"{finding_event.duration_ms}ms")
    return results


def validate_finding_event(event_dict: dict) -> list[str]:
    """Validate a FindingEvent dict has all required fields for the TS assessor."""
    errors = []
    required_top = ["scanId", "agentName", "findings", "agentResult"]
    for key in required_top:
        if key not in event_dict:
            errors.append(f"Missing top-level key: {key}")

    ar = event_dict.get("agentResult", {})
    required_ar = ["agentName", "agentVersion", "rulesetVersion", "status", "findingCount", "durationMs"]
    for key in required_ar:
        if key not in ar:
            errors.append(f"Missing agentResult key: {key}")

    for i, finding in enumerate(event_dict.get("findings", [])):
        required_f = ["type", "file", "lineStart", "lineEnd", "severity", "confidence"]
        for key in required_f:
            if key not in finding:
                errors.append(f"Finding[{i}] missing key: {key}")

        valid_types = {"security", "license", "quality", "policy", "dependency", "ai-detection"}
        if finding.get("type") not in valid_types:
            errors.append(f"Finding[{i}] invalid type: {finding.get('type')}")

        valid_severities = {"critical", "high", "medium", "low", "info"}
        if finding.get("severity") not in valid_severities:
            errors.append(f"Finding[{i}] invalid severity: {finding.get('severity')}")

    return errors


def main() -> int:
    print("=" * 70)
    print("SENTINEL E2E Integration Test: Full Agent Pipeline")
    print("=" * 70)

    # Phase 1: Build realistic payload
    print("\n[Phase 1] Building realistic diff payload...")
    event = build_realistic_payload()
    print(f"  Scan ID: {event.scan_id}")
    print(f"  Files: {len(event.files)}")
    print(f"  Security level: {event.scan_config.security_level}")

    # Phase 2: Run all 6 agents
    print("\n[Phase 2] Running all 6 analysis agents...")
    results = run_all_agents(event)

    # Phase 3: Validate output format
    print("\n[Phase 3] Validating FindingEvent format compatibility...")
    all_errors = []
    for result in results:
        errors = validate_finding_event(result)
        if errors:
            all_errors.extend(errors)
            print(f"  FAIL {result.get('agentName', '?')}: {errors}")
        else:
            print(f"  OK   {result.get('agentName', '?')}: valid FindingEvent")

    # Phase 4: Verify cross-agent consistency
    print("\n[Phase 4] Verifying cross-agent consistency...")
    agent_names = {r["agentName"] for r in results}
    expected_agents = {"security", "ip-license", "dependency",
                       "ai-detector", "quality", "policy"}

    missing = expected_agents - agent_names
    if missing:
        print(f"  FAIL Missing agents: {missing}")
        all_errors.append(f"Missing agents: {missing}")
    else:
        print(f"  OK   All 6 agents reported results")

    all_statuses = {r["agentResult"]["status"] for r in results}
    print(f"  Agent statuses: {all_statuses}")
    if "error" in all_statuses:
        errored = [r["agentName"] for r in results if r["agentResult"]["status"] == "error"]
        print(f"  WARN Agents with errors: {errored}")

    # Phase 5: Aggregate findings
    print("\n[Phase 5] Findings summary...")
    total_findings = 0
    by_type = {}
    by_severity = {}
    for result in results:
        for finding in result["findings"]:
            total_findings += 1
            ftype = finding["type"]
            sev = finding["severity"]
            by_type[ftype] = by_type.get(ftype, 0) + 1
            by_severity[sev] = by_severity.get(sev, 0) + 1

    print(f"  Total findings: {total_findings}")
    print(f"  By type: {json.dumps(by_type, indent=4)}")
    print(f"  By severity: {json.dumps(by_severity, indent=4)}")

    # Phase 6: Verify JSON serialization (what would be sent to TS assessor)
    print("\n[Phase 6] Verifying JSON round-trip serialization...")
    try:
        serialized = json.dumps(results, indent=2)
        deserialized = json.loads(serialized)
        assert len(deserialized) == len(results)
        print(f"  OK   Serialized {len(serialized)} bytes, round-trip intact")
    except Exception as e:
        print(f"  FAIL Serialization error: {e}")
        all_errors.append(f"Serialization error: {e}")

    # Final verdict
    print("\n" + "=" * 70)
    if all_errors:
        print(f"FAIL: {len(all_errors)} errors found")
        for err in all_errors:
            print(f"  - {err}")
        return 1
    elif total_findings == 0:
        print("WARN: All agents passed but produced 0 findings (payload may be too benign)")
        return 0
    else:
        print(f"PASS: All 6 agents ran successfully, {total_findings} findings produced")
        print("      Output format validated for TypeScript assessor compatibility")
        return 0


if __name__ == "__main__":
    sys.exit(main())
