from sentinel_aidetector.markers import detect_markers


def test_no_markers_in_clean_code():
    code = """
def hello():
    print("Hello, world!")
"""
    assert detect_markers(code) == []


def test_detect_generated_by_copilot():
    code = "# Generated by GitHub Copilot\ndef foo(): pass"
    matches = detect_markers(code)
    assert len(matches) >= 1
    tools = {m.tool for m in matches}
    assert "copilot" in tools or "ai-generic" in tools


def test_detect_cursor_marker():
    code = "// @cursor suggested this implementation\nconst x = 1;"
    matches = detect_markers(code)
    assert len(matches) >= 1
    assert any(m.tool == "cursor" for m in matches)


def test_detect_claude_marker():
    code = "# This function was generated by Claude\ndef bar(): pass"
    matches = detect_markers(code)
    assert len(matches) >= 1
    tools = {m.tool for m in matches}
    assert "claude" in tools or "ai-generic" in tools


def test_detect_chatgpt_marker():
    code = "# Created with ChatGPT assistance\nresult = compute()"
    matches = detect_markers(code)
    assert len(matches) >= 1
    assert any(m.tool == "chatgpt" for m in matches)


def test_detect_multiple_markers():
    code = """# Generated by AI
# GitHub Copilot suggested this
# ChatGPT helped refine it
def complex_function():
    pass
"""
    matches = detect_markers(code)
    assert len(matches) >= 3


def test_marker_line_numbers():
    code = "line one\n# Generated by Copilot\nline three"
    matches = detect_markers(code)
    copilot_matches = [m for m in matches if m.tool == "copilot"]
    assert len(copilot_matches) >= 1
    assert copilot_matches[0].line_number == 2
