from sentinel_agents.types import Confidence, DiffEvent, DiffFile, DiffHunk, ScanConfig

from sentinel_aidetector.agent import AIDetectorAgent


def _make_event(files: list[DiffFile]) -> DiffEvent:
    return DiffEvent(
        scan_id="scan_test",
        project_id="proj_1",
        commit_hash="abc123",
        branch="main",
        author="dev@test.com",
        timestamp="2026-03-09T12:00:00Z",
        files=files,
        scan_config=ScanConfig(
            security_level="standard", license_policy="MIT", quality_threshold=0.7
        ),
    )


def test_clean_code_low_probability():
    """Clean human-like code with no markers should produce low or no findings."""
    files = [
        DiffFile(
            path="utils.py",
            language="python",
            hunks=[
                DiffHunk(
                    old_start=1,
                    old_count=0,
                    new_start=1,
                    new_count=3,
                    content="+import os\n+x = 1\n+print(x)\n",
                )
            ],
            ai_score=0.0,
        )
    ]
    agent = AIDetectorAgent()
    result = agent.run_scan(_make_event(files))
    assert result.status == "completed"
    # Few lines + no markers -> low or no detection
    for f in result.findings:
        assert f.extra["trace"]["overallScore"] < 0.5


def test_detects_marker_annotated_code():
    """Code with AI tool markers should be flagged."""
    code = (
        "+# Generated by GitHub Copilot\n"
        "+def calculate_sum(numbers):\n"
        "+    total_sum = 0\n"
        "+    for number in numbers:\n"
        "+        total_sum += number\n"
        "+    return total_sum\n"
    )
    files = [
        DiffFile(
            path="math_utils.py",
            language="python",
            hunks=[
                DiffHunk(old_start=1, old_count=0, new_start=1, new_count=6, content=code)
            ],
            ai_score=0.9,
        )
    ]
    agent = AIDetectorAgent()
    result = agent.run_scan(_make_event(files))
    assert result.status == "completed"
    assert len(result.findings) >= 1
    finding = result.findings[0]
    assert finding.type == "ai-detection"
    assert finding.extra["trace"]["signals"]["markers"]["detail"]["matchCount"] >= 1
    assert finding.extra["trace"]["overallScore"] > 0.2


def test_bulk_commit_increases_probability():
    """A very large diff should increase AI detection probability."""
    lines = [f"+variable_{i} = compute_value_{i}()" for i in range(600)]
    content = "\n".join(lines)
    files = [
        DiffFile(
            path="generated.py",
            language="python",
            hunks=[
                DiffHunk(
                    old_start=1, old_count=0, new_start=1, new_count=600, content=content
                )
            ],
            ai_score=0.5,
        )
    ]
    agent = AIDetectorAgent()
    result = agent.run_scan(_make_event(files))
    assert result.status == "completed"
    assert len(result.findings) >= 1
    assert result.findings[0].extra["trace"]["signals"]["timing"]["detail"]["linesChanged"] == 600


def test_empty_diff_no_findings():
    """Empty files should produce no findings."""
    files = [
        DiffFile(
            path="empty.py",
            language="python",
            hunks=[],
            ai_score=0.0,
        )
    ]
    agent = AIDetectorAgent()
    result = agent.run_scan(_make_event(files))
    assert result.status == "completed"
    assert len(result.findings) == 0


def test_finding_fields():
    """Verify finding has correct structure and fields."""
    code = "+# Generated by ChatGPT\n+def hello(): pass\n"
    files = [
        DiffFile(
            path="hello.py",
            language="python",
            hunks=[
                DiffHunk(old_start=1, old_count=0, new_start=1, new_count=2, content=code)
            ],
            ai_score=0.8,
        )
    ]
    agent = AIDetectorAgent()
    result = agent.run_scan(_make_event(files))
    assert result.agent_name == "ai-detector"
    if result.findings:
        f = result.findings[0]
        assert f.scanner == "ai-detector"
        assert f.category == "ai-generated"
        assert "trace" in f.extra
        assert 0.0 <= f.extra["trace"]["overallScore"] <= 1.0


def test_finding_has_ast_entropy_fields():
    """Findings should include AST entropy breakdown."""
    code = "+# Generated by ChatGPT\n+def hello(): pass\n"
    files = [
        DiffFile(
            path="hello.py",
            language="python",
            hunks=[DiffHunk(1, 0, 1, 2, code)],
            ai_score=0.8,
        )
    ]
    agent = AIDetectorAgent()
    result = agent.run_scan(_make_event(files))
    if result.findings:
        extra = result.findings[0].extra
        signals = extra["trace"]["signals"]
        assert "tokenEntropy" in signals["entropy"]["detail"]
        assert "structureEntropy" in signals["entropy"]["detail"]
        assert "namingEntropy" in signals["entropy"]["detail"]
        assert "isBurst" in signals["timing"]["detail"]


def test_calibrator_adjusts_confidence():
    """When calibrator has high precision, confidence should be boosted."""
    from agent_core.correlation.confidence import ConfidenceCalibrator

    calibrator = ConfidenceCalibrator()
    # Record high accuracy: 10/10 accurate
    for _ in range(10):
        calibrator.record_feedback("ai-detector", "ai-generated", was_accurate=True)

    code = "+# Generated by ChatGPT\n+def hello(): pass\n"
    files = [
        DiffFile(
            path="hello.py",
            language="python",
            hunks=[DiffHunk(1, 0, 1, 2, code)],
            ai_score=0.8,
        )
    ]

    # Without calibrator
    agent_plain = AIDetectorAgent()
    result_plain = agent_plain.run_scan(_make_event(files))

    # With calibrator
    agent_cal = AIDetectorAgent(calibrator=calibrator)
    result_cal = agent_cal.run_scan(_make_event(files))

    if result_plain.findings and result_cal.findings:
        conf_order = [Confidence.LOW, Confidence.MEDIUM, Confidence.HIGH]
        plain_idx = conf_order.index(result_plain.findings[0].confidence)
        cal_idx = conf_order.index(result_cal.findings[0].confidence)
        # Calibrated should be >= plain confidence
        assert cal_idx >= plain_idx


def test_version_updated():
    agent = AIDetectorAgent()
    assert agent.version == "0.2.0"
