apiVersion: v1
kind: Service
metadata:
  name: sentinel-api
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "sentinel.labels" . | nindent 4 }}
spec:
  selector:
    app: sentinel-api
  ports:
    - port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
  type: ClusterIP
