{{- range $name, $worker := .Values.workers }}
{{- if $worker.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sentinel.fullname" $ }}-worker-{{ $name }}
  labels:
    {{- include "sentinel.labels" $ | nindent 4 }}
    app.kubernetes.io/component: worker-{{ $name }}
spec:
  replicas: {{ $worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "sentinel.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: worker-{{ $name }}
  template:
    metadata:
      labels:
        {{- include "sentinel.selectorLabels" $ | nindent 8 }}
        app.kubernetes.io/component: worker-{{ $name }}
        sentinel.io/tier: standard
    spec:
      securityContext:
        {{- include "sentinel.podSecurityContext" $ | nindent 8 }}
      {{- with $.Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $name }}
          image: {{ include "sentinel.image" (dict "global" $.Values.global "repository" $.Values.api.image.repository "tag" ($.Values.api.image.tag | default $.Chart.AppVersion)) }}
          command:
            {{- toYaml $worker.command | nindent 12 }}
          env:
            {{- include "sentinel.commonEnv" $ | nindent 12 }}
          resources:
            {{- toYaml $worker.resources | nindent 12 }}
          securityContext:
            {{- include "sentinel.containerSecurityContext" $ | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
{{- end }}
{{- end }}
