apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentinel-worker
  namespace: {{ .Values.global.namespace }}
  labels:
    app: sentinel-worker
    {{- include "sentinel.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: sentinel-worker
  template:
    metadata:
      labels:
        app: sentinel-worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.worker.image }}:{{ .Values.global.imageTag }}"
          command: ["node", "apps/api/dist/worker.js"]
          envFrom:
            - configMapRef:
                name: sentinel-config
            - secretRef:
                name: sentinel-secrets
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
