import { describe, it, expect } from "vitest";
import { getDefaultBranding, type BrandingContext } from "../reports/branding.js";

describe("BrandingContext", () => {
  it("returns defaults with org name", () => {
    const b = getDefaultBranding("Acme Corp");
    expect(b.orgName).toBe("Acme Corp");
    expect(b.accentColor).toBe("#2563EB");
    expect(b.footerText).toBe("Generated by Sentinel");
    expect(b.logoUrl).toBeUndefined();
    expect(b.confidentialityBanner).toBeUndefined();
  });

  it("merges partial overrides", () => {
    const b = getDefaultBranding("Acme Corp", { accentColor: "#FF0000", confidentialityBanner: "TOP SECRET" });
    expect(b.accentColor).toBe("#FF0000");
    expect(b.confidentialityBanner).toBe("TOP SECRET");
    expect(b.orgName).toBe("Acme Corp");
  });
});
