import { describe, it, expect } from "vitest";
import { createElement } from "react";
import { renderToBuffer } from "@react-pdf/renderer";
import { Document, Page } from "@react-pdf/renderer";
import { PageHeader } from "../reports/components/PageHeader.js";
import { PageFooter } from "../reports/components/PageFooter.js";

describe("PageHeader", () => {
  it("renders without crashing", async () => {
    const doc = createElement(Document, null,
      createElement(Page, { size: "A4" },
        createElement(PageHeader, {
          title: "Test Report",
          branding: { orgName: "Acme", accentColor: "#2563EB", footerText: "test" },
        }),
      ),
    );
    const buffer = await renderToBuffer(doc as any);
    expect(buffer.length).toBeGreaterThan(0);
  });

  it("renders with confidentiality banner", async () => {
    const doc = createElement(Document, null,
      createElement(Page, { size: "A4" },
        createElement(PageHeader, {
          title: "Confidential Report",
          branding: {
            orgName: "Acme",
            accentColor: "#2563EB",
            footerText: "test",
            confidentialityBanner: "CONFIDENTIAL - DO NOT DISTRIBUTE",
          },
        }),
      ),
    );
    const buffer = await renderToBuffer(doc as any);
    expect(buffer.length).toBeGreaterThan(0);
  });
});

describe("PageFooter", () => {
  it("renders without crashing", async () => {
    const doc = createElement(Document, null,
      createElement(Page, { size: "A4" },
        createElement(PageFooter, {
          branding: { orgName: "Acme", accentColor: "#2563EB", footerText: "Generated by Sentinel" },
          generatedAt: "2026-03-15T00:00:00Z",
        }),
      ),
    );
    const buffer = await renderToBuffer(doc as any);
    expect(buffer.length).toBeGreaterThan(0);
  });
});
