import { Document, Page, View, Text, StyleSheet } from "@react-pdf/renderer";
import { PageHeader } from "./components/PageHeader.js";
import { PageFooter } from "./components/PageFooter.js";
import type { BrandingContext } from "./branding.js";
import type { AssessmentResult } from "../types.js";

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: "Helvetica", fontSize: 10 },
  section: { marginBottom: 16 },
  sectionTitle: { fontSize: 14, fontWeight: "bold", marginBottom: 8, color: "#1f2937" },
  evidenceItem: { marginBottom: 8, padding: 8, backgroundColor: "#f9fafb", borderRadius: 4 },
  evidenceType: { fontSize: 9, fontWeight: "bold", color: "#374151" },
  evidenceHash: { fontSize: 7, color: "#9ca3af", fontFamily: "Courier" },
  evidenceData: { fontSize: 8, color: "#4b5563", marginTop: 4 },
});

export interface EvidenceItem {
  type: string;
  hash: string;
  prevHash: string | null;
  data: unknown;
  createdAt: string;
}

export interface AuditEvidenceData {
  frameworkName: string;
  assessment: AssessmentResult;
  orgName: string;
  evidenceRecords: EvidenceItem[];
  chainVerification: { valid: boolean; checkedCount: number };
  generatedAt: string;
}

export function AuditEvidenceReport({ data, branding }: { data: AuditEvidenceData; branding?: BrandingContext }) {
  const { frameworkName, assessment, orgName, evidenceRecords, chainVerification, generatedAt } = data;
  const effectiveBranding: BrandingContext = branding ?? { orgName, accentColor: "#2563EB", footerText: "Generated by SENTINEL" };

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <PageHeader title="Audit Evidence Report" branding={effectiveBranding} />

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Assessment Summary</Text>
          <Text>Score: {Math.round(assessment.score * 100)}% — {assessment.verdict.replace(/_/g, " ")}</Text>
          <Text>Controls evaluated: {assessment.controlScores.length}</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Evidence Chain Integrity</Text>
          <Text>Status: {chainVerification.valid ? "VERIFIED" : "BROKEN"}</Text>
          <Text>Records verified: {chainVerification.checkedCount}</Text>
        </View>
      </Page>

      {evidenceRecords.length > 0 && (
        <Page size="A4" style={styles.page}>
          <Text style={styles.sectionTitle}>Evidence Records</Text>
          {evidenceRecords.map((record, i) => (
            <View key={i} style={styles.evidenceItem}>
              <Text style={styles.evidenceType}>{record.type} — {record.createdAt}</Text>
              <Text style={styles.evidenceHash}>Hash: {record.hash}</Text>
              {record.prevHash && <Text style={styles.evidenceHash}>Prev: {record.prevHash}</Text>}
              <Text style={styles.evidenceData}>{JSON.stringify(record.data).slice(0, 200)}</Text>
            </View>
          ))}
          <PageFooter branding={effectiveBranding} generatedAt={generatedAt} />
        </Page>
      )}
    </Document>
  );
}
