export interface BrandingContext {
  orgName: string;
  logoUrl?: string;
  accentColor: string;
  footerText: string;
  confidentialityBanner?: string;
}

export function getDefaultBranding(orgName: string, overrides?: Partial<BrandingContext>): BrandingContext {
  return {
    orgName,
    accentColor: "#2563EB",
    footerText: "Generated by Sentinel",
    ...overrides,
  };
}
