import { Document, Page, View, Text, StyleSheet } from "@react-pdf/renderer";
import { ScoreDonut } from "./components/ScoreDonut.js";
import { ControlTable } from "./components/ControlTable.js";
import type { AssessmentResult } from "../types.js";

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: "Helvetica", fontSize: 10 },
  title: { fontSize: 20, fontWeight: "bold", marginBottom: 4, color: "#111827" },
  subtitle: { fontSize: 12, color: "#6b7280", marginBottom: 20 },
  section: { marginBottom: 16 },
  sectionTitle: { fontSize: 14, fontWeight: "bold", marginBottom: 8, color: "#1f2937" },
  row: { flexDirection: "row", alignItems: "center", gap: 16 },
  verdictText: { fontSize: 14, fontWeight: "bold" },
  footer: { position: "absolute", bottom: 30, left: 40, right: 40, textAlign: "center", fontSize: 8, color: "#9ca3af" },
});

export interface ComplianceSummaryData {
  frameworkName: string;
  frameworkVersion: string;
  assessment: AssessmentResult;
  orgName: string;
  generatedAt: string;
}

export function ComplianceSummaryReport({ data }: { data: ComplianceSummaryData }) {
  const { frameworkName, frameworkVersion, assessment, orgName, generatedAt } = data;
  const verdictColor = assessment.verdict === "compliant" ? "#22c55e"
    : assessment.verdict === "partially_compliant" ? "#eab308"
    : assessment.verdict === "needs_remediation" ? "#f97316" : "#ef4444";

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>Compliance Summary Report</Text>
        <Text style={styles.subtitle}>{frameworkName} v{frameworkVersion} — {orgName}</Text>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Overall Score</Text>
          <View style={styles.row}>
            <ScoreDonut score={assessment.score} />
            <View>
              <Text style={[styles.verdictText, { color: verdictColor }]}>
                {assessment.verdict.replace(/_/g, " ").toUpperCase()}
              </Text>
              <Text>Score: {Math.round(assessment.score * 100)}%</Text>
            </View>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Control Breakdown</Text>
          <ControlTable controlScores={assessment.controlScores} />
        </View>

        <Text style={styles.footer}>
          Generated by SENTINEL on {generatedAt} | {frameworkName} v{frameworkVersion}
        </Text>
      </Page>
    </Document>
  );
}
