import { Document, Page, View, Text, StyleSheet } from "@react-pdf/renderer";
import { ScoreDonut } from "./components/ScoreDonut.js";
import { ControlTable } from "./components/ControlTable.js";
import { PageHeader } from "./components/PageHeader.js";
import { PageFooter } from "./components/PageFooter.js";
import type { BrandingContext } from "./branding.js";
import type { AssessmentResult } from "../types.js";

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: "Helvetica", fontSize: 10 },
  section: { marginBottom: 16 },
  sectionTitle: { fontSize: 14, fontWeight: "bold", marginBottom: 8, color: "#1f2937" },
  row: { flexDirection: "row", alignItems: "center", gap: 16 },
  verdictText: { fontSize: 14, fontWeight: "bold" },
});

export interface ComplianceSummaryData {
  frameworkName: string;
  frameworkVersion: string;
  assessment: AssessmentResult;
  orgName: string;
  generatedAt: string;
}

export function ComplianceSummaryReport({ data, branding }: { data: ComplianceSummaryData; branding?: BrandingContext }) {
  const { frameworkName, frameworkVersion, assessment, orgName, generatedAt } = data;
  const effectiveBranding: BrandingContext = branding ?? { orgName, accentColor: "#2563EB", footerText: "Generated by SENTINEL" };
  const verdictColor = assessment.verdict === "compliant" ? "#22c55e"
    : assessment.verdict === "partially_compliant" ? "#eab308"
    : assessment.verdict === "needs_remediation" ? "#f97316" : "#ef4444";

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <PageHeader title="Compliance Summary Report" branding={effectiveBranding} />

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Overall Score</Text>
          <View style={styles.row}>
            <ScoreDonut score={assessment.score} />
            <View>
              <Text style={[styles.verdictText, { color: verdictColor }]}>
                {assessment.verdict.replace(/_/g, " ").toUpperCase()}
              </Text>
              <Text>Score: {Math.round(assessment.score * 100)}%</Text>
            </View>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Control Breakdown</Text>
          <ControlTable controlScores={assessment.controlScores} />
        </View>

        <PageFooter branding={effectiveBranding} generatedAt={generatedAt} />
      </Page>
    </Document>
  );
}
