import { Document, Page, View, Text, StyleSheet } from "@react-pdf/renderer";
import { PageHeader } from "./components/index.js";
import { PageFooter } from "./components/index.js";
import type { BrandingContext } from "./branding.js";

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: "Helvetica", fontSize: 10 },
  section: { marginBottom: 16 },
  sectionTitle: { fontSize: 14, fontWeight: "bold", marginBottom: 8, color: "#1f2937" },
  row: { flexDirection: "row", marginBottom: 4 },
  label: { width: 200, fontWeight: "bold" },
  value: { flex: 1 },
  bodyText: { marginBottom: 8, lineHeight: 1.5 },
});

export interface MonitoringPlanData {
  systemName: string;
  generatedAt: string;
  sections: {
    monitoringScope: string;
    dataCollection: string;
    performanceMonitoring: string;
    incidentReporting: string;
    correctiveActions: string;
    reviewCadence: string;
    qmsIntegration: string;
  };
}

export function EuAiActMonitoringReport({ data, branding }: { data: MonitoringPlanData; branding?: BrandingContext }) {
  const { systemName, generatedAt, sections } = data;
  const effectiveBranding: BrandingContext = branding ?? { orgName: systemName, accentColor: "#2563EB", footerText: "Generated by SENTINEL" };

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <PageHeader title="EU AI Act - Post-Market Monitoring Plan" branding={effectiveBranding} />

        {/* System Info */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>1. Plan Overview</Text>
          <View style={styles.row}>
            <Text style={styles.label}>AI System Name:</Text>
            <Text style={styles.value}>{systemName}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Generated:</Text>
            <Text style={styles.value}>{generatedAt}</Text>
          </View>
        </View>

        {/* Monitoring Scope */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>2. Monitoring Scope</Text>
          <Text style={styles.bodyText}>{sections.monitoringScope}</Text>
        </View>

        {/* Data Collection */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>3. Data Collection</Text>
          <Text style={styles.bodyText}>{sections.dataCollection}</Text>
        </View>

        {/* Performance Monitoring */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>4. Performance Monitoring</Text>
          <Text style={styles.bodyText}>{sections.performanceMonitoring}</Text>
        </View>

        {/* Incident Reporting */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>5. Incident Reporting</Text>
          <Text style={styles.bodyText}>{sections.incidentReporting}</Text>
        </View>

        {/* Corrective Actions */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>6. Corrective Actions</Text>
          <Text style={styles.bodyText}>{sections.correctiveActions}</Text>
        </View>

        {/* Review Cadence */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>7. Review Cadence</Text>
          <Text style={styles.bodyText}>{sections.reviewCadence}</Text>
        </View>

        {/* QMS Integration */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>8. Quality Management System Integration</Text>
          <Text style={styles.bodyText}>{sections.qmsIntegration}</Text>
        </View>

        <PageFooter branding={effectiveBranding} generatedAt={generatedAt} />
      </Page>
    </Document>
  );
}
