import { Document, Page, View, Text, StyleSheet } from "@react-pdf/renderer";
import { PageHeader } from "./components/index.js";
import { PageFooter } from "./components/index.js";
import type { BrandingContext } from "./branding.js";

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: "Helvetica", fontSize: 10 },
  section: { marginBottom: 16 },
  sectionTitle: { fontSize: 14, fontWeight: "bold", marginBottom: 8, color: "#1f2937" },
  row: { flexDirection: "row", marginBottom: 4 },
  label: { width: 200, fontWeight: "bold" },
  value: { flex: 1 },
  bodyText: { marginBottom: 8, lineHeight: 1.5 },
});

export interface InstructionsData {
  systemName: string;
  provider: { name: string; contact: string; support: string };
  generatedAt: string;
  sections: {
    intendedPurpose: string;
    transparencyObligations: string;
    humanOversightInstructions: string;
    knownLimitations: string;
    inputDataSpecifications: string;
    maintenanceUpdates: string;
  };
}

export function EuAiActInstructionsReport({ data, branding }: { data: InstructionsData; branding?: BrandingContext }) {
  const { systemName, provider, generatedAt, sections } = data;
  const effectiveBranding: BrandingContext = branding ?? { orgName: provider.name, accentColor: "#2563EB", footerText: "Generated by SENTINEL" };

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <PageHeader title="EU AI Act - Instructions for Use" branding={effectiveBranding} />

        {/* System and Provider Info */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>1. System Information</Text>
          <View style={styles.row}>
            <Text style={styles.label}>AI System Name:</Text>
            <Text style={styles.value}>{systemName}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Provider:</Text>
            <Text style={styles.value}>{provider.name}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Contact:</Text>
            <Text style={styles.value}>{provider.contact}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Support:</Text>
            <Text style={styles.value}>{provider.support}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Generated:</Text>
            <Text style={styles.value}>{generatedAt}</Text>
          </View>
        </View>

        {/* Intended Purpose */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>2. Intended Purpose</Text>
          <Text style={styles.bodyText}>{sections.intendedPurpose}</Text>
        </View>

        {/* Transparency Obligations */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>3. Transparency Obligations</Text>
          <Text style={styles.bodyText}>{sections.transparencyObligations}</Text>
        </View>

        {/* Human Oversight Instructions */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>4. Human Oversight Instructions</Text>
          <Text style={styles.bodyText}>{sections.humanOversightInstructions}</Text>
        </View>

        {/* Known Limitations */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>5. Known Limitations</Text>
          <Text style={styles.bodyText}>{sections.knownLimitations}</Text>
        </View>

        {/* Input Data Specifications */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>6. Input Data Specifications</Text>
          <Text style={styles.bodyText}>{sections.inputDataSpecifications}</Text>
        </View>

        {/* Maintenance and Updates */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>7. Maintenance and Updates</Text>
          <Text style={styles.bodyText}>{sections.maintenanceUpdates}</Text>
        </View>

        <PageFooter branding={effectiveBranding} generatedAt={generatedAt} />
      </Page>
    </Document>
  );
}
