import { Document, Page, View, Text, StyleSheet } from "@react-pdf/renderer";
import { PageHeader } from "./components/index.js";
import { PageFooter } from "./components/index.js";
import type { BrandingContext } from "./branding.js";

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: "Helvetica", fontSize: 10 },
  section: { marginBottom: 16 },
  sectionTitle: { fontSize: 14, fontWeight: "bold", marginBottom: 8, color: "#1f2937" },
  row: { flexDirection: "row", marginBottom: 4 },
  label: { width: 200, fontWeight: "bold" },
  value: { flex: 1 },
  bodyText: { marginBottom: 8, lineHeight: 1.5 },
  table: { marginTop: 8 },
  tableRow: { flexDirection: "row", borderBottomWidth: 1, borderBottomColor: "#e5e7eb", paddingVertical: 4 },
  tableHeader: { fontWeight: "bold", backgroundColor: "#f9fafb" },
  colCode: { width: 80 },
  colTitle: { flex: 1 },
  colStatus: { width: 80 },
  standardItem: { marginBottom: 3, paddingLeft: 12 },
  signatureBlock: { marginTop: 30, paddingTop: 16, borderTopWidth: 1, borderTopColor: "#e5e7eb" },
  signatureLine: { width: 200, borderBottomWidth: 1, borderBottomColor: "#111827", marginTop: 40, marginBottom: 4 },
  signatureLabel: { fontSize: 9, color: "#6b7280" },
});

function statusColor(status: string): string {
  if (status === "compliant") return "#22c55e";
  if (status === "partial") return "#eab308";
  return "#ef4444";
}

export interface DeclarationData {
  declarationId: string;
  date: string;
  provider: { name: string; address: string; contact: string };
  system: { name: string; version: string; identifier: string };
  conformityAssessment: string;
  standardsApplied: string[];
  controlStatuses: Array<{ code: string; title: string; status: string }>;
  signatoryName: string;
  signatoryPosition: string;
}

export function EuAiActDeclarationReport({ data, branding }: { data: DeclarationData; branding?: BrandingContext }) {
  const { declarationId, date, provider, system, conformityAssessment, standardsApplied, controlStatuses, signatoryName, signatoryPosition } = data;
  const effectiveBranding: BrandingContext = branding ?? { orgName: provider.name, accentColor: "#2563EB", footerText: "Generated by SENTINEL" };

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <PageHeader title="EU AI Act - Declaration of Conformity" branding={effectiveBranding} />

        {/* Declaration Metadata */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Declaration Details</Text>
          <View style={styles.row}>
            <Text style={styles.label}>Declaration ID:</Text>
            <Text style={styles.value}>{declarationId}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Date:</Text>
            <Text style={styles.value}>{date}</Text>
          </View>
        </View>

        {/* Provider Information */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Provider Information</Text>
          <View style={styles.row}>
            <Text style={styles.label}>Name:</Text>
            <Text style={styles.value}>{provider.name}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Address:</Text>
            <Text style={styles.value}>{provider.address}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Contact:</Text>
            <Text style={styles.value}>{provider.contact}</Text>
          </View>
        </View>

        {/* AI System Information */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>AI System</Text>
          <View style={styles.row}>
            <Text style={styles.label}>System Name:</Text>
            <Text style={styles.value}>{system.name}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Version:</Text>
            <Text style={styles.value}>{system.version}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Unique Identifier:</Text>
            <Text style={styles.value}>{system.identifier}</Text>
          </View>
        </View>

        {/* Conformity Assessment */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Conformity Assessment Procedure</Text>
          <Text style={styles.bodyText}>{conformityAssessment}</Text>
        </View>

        {/* Standards Applied */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Harmonised Standards Applied</Text>
          {standardsApplied.map((std, i) => (
            <Text key={i} style={styles.standardItem}>- {std}</Text>
          ))}
        </View>

        {/* Control Statuses */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Control Compliance Status</Text>
          <View style={styles.table}>
            <View style={[styles.tableRow, styles.tableHeader]}>
              <Text style={styles.colCode}>Code</Text>
              <Text style={styles.colTitle}>Title</Text>
              <Text style={styles.colStatus}>Status</Text>
            </View>
            {controlStatuses.map((c, i) => (
              <View key={i} style={styles.tableRow}>
                <Text style={styles.colCode}>{c.code}</Text>
                <Text style={styles.colTitle}>{c.title}</Text>
                <Text style={{ ...styles.colStatus, color: statusColor(c.status) }}>{c.status}</Text>
              </View>
            ))}
          </View>
        </View>

        {/* Signature Block */}
        <View style={styles.signatureBlock}>
          <Text style={styles.bodyText}>
            I hereby declare that the above-named AI system is in conformity with the relevant provisions of the EU AI Act (Regulation (EU) 2024/1689).
          </Text>
          <View style={styles.signatureLine} />
          <Text style={styles.signatureLabel}>{signatoryName}</Text>
          <Text style={styles.signatureLabel}>{signatoryPosition}</Text>
          <Text style={styles.signatureLabel}>{date}</Text>
        </View>

        <PageFooter branding={effectiveBranding} generatedAt={date} />
      </Page>
    </Document>
  );
}
