import { Document, Page, View, Text, StyleSheet } from "@react-pdf/renderer";
import { PageHeader } from "./components/index.js";
import { PageFooter } from "./components/index.js";
import type { BrandingContext } from "./branding.js";

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: "Helvetica", fontSize: 10 },
  section: { marginBottom: 16 },
  sectionTitle: { fontSize: 14, fontWeight: "bold", marginBottom: 8, color: "#1f2937" },
  subsectionTitle: { fontSize: 12, fontWeight: "bold", marginBottom: 6, color: "#374151" },
  row: { flexDirection: "row", marginBottom: 4 },
  label: { width: 200, fontWeight: "bold" },
  value: { flex: 1 },
  bodyText: { marginBottom: 8, lineHeight: 1.5 },
  table: { marginTop: 8 },
  tableRow: { flexDirection: "row", borderBottomWidth: 1, borderBottomColor: "#e5e7eb", paddingVertical: 4 },
  tableHeader: { fontWeight: "bold", backgroundColor: "#f9fafb" },
  checkRow: { flexDirection: "row", marginBottom: 3 },
  checkBox: { width: 14, marginRight: 6, fontWeight: "bold" },
  checkLabel: { flex: 1 },
  colFile: { flex: 1 },
  colSha: { width: 120, fontSize: 7 },
  colControl: { width: 70 },
  colDate: { width: 80 },
});

export interface TechnicalDocData {
  systemName: string;
  provider: string;
  version: string;
  generatedAt: string;
  sections: {
    systemOverview: string;
    riskClassification: { text: string; requirements: Array<{ key: string; label: string; completed: boolean }> };
    dataGovernance: { text: string; requirements: Array<{ key: string; label: string; completed: boolean }> };
    algorithmDesign: string;
    humanOversight: { text: string; requirements: Array<{ key: string; label: string; completed: boolean }> };
    accuracyRobustness: { text: string; requirements: Array<{ key: string; label: string; completed: boolean }> };
    logging: { text: string; requirements: Array<{ key: string; label: string; completed: boolean }> };
  };
  evidenceIndex: Array<{ fileName: string; sha256: string; controlCode: string; uploadedAt: string }>;
}

function RequirementChecklist({ requirements }: { requirements: Array<{ key: string; label: string; completed: boolean }> }) {
  return (
    <View style={{ marginTop: 4, marginBottom: 8 }}>
      {requirements.map((req, i) => (
        <View key={i} style={styles.checkRow}>
          <Text style={styles.checkBox}>{req.completed ? "[X]" : "[ ]"}</Text>
          <Text style={styles.checkLabel}>{req.key} - {req.label}</Text>
        </View>
      ))}
    </View>
  );
}

function SectionWithRequirements({ title, text, requirements }: { title: string; text: string; requirements: Array<{ key: string; label: string; completed: boolean }> }) {
  return (
    <View style={styles.section}>
      <Text style={styles.subsectionTitle}>{title}</Text>
      <Text style={styles.bodyText}>{text}</Text>
      <RequirementChecklist requirements={requirements} />
    </View>
  );
}

export function EuAiActTechnicalDocReport({ data, branding }: { data: TechnicalDocData; branding?: BrandingContext }) {
  const { systemName, provider, version, generatedAt, sections, evidenceIndex } = data;
  const effectiveBranding: BrandingContext = branding ?? { orgName: provider, accentColor: "#2563EB", footerText: "Generated by SENTINEL" };

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <PageHeader title="EU AI Act - Technical Documentation" branding={effectiveBranding} />

        {/* Section 1: Document Metadata */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>1. Document Information</Text>
          <View style={styles.row}>
            <Text style={styles.label}>AI System Name:</Text>
            <Text style={styles.value}>{systemName}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Provider:</Text>
            <Text style={styles.value}>{provider}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Version:</Text>
            <Text style={styles.value}>{version}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Generated:</Text>
            <Text style={styles.value}>{generatedAt}</Text>
          </View>
        </View>

        {/* Section 2: System Overview */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>2. System Overview</Text>
          <Text style={styles.bodyText}>{sections.systemOverview}</Text>
        </View>

        {/* Section 3: Risk Classification */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>3. Risk Classification</Text>
          <Text style={styles.bodyText}>{sections.riskClassification.text}</Text>
          <RequirementChecklist requirements={sections.riskClassification.requirements} />
        </View>

        {/* Section 4: Data Governance */}
        <SectionWithRequirements
          title="4. Data Governance"
          text={sections.dataGovernance.text}
          requirements={sections.dataGovernance.requirements}
        />

        {/* Section 5: Algorithm Design */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>5. Algorithm Design and Development</Text>
          <Text style={styles.bodyText}>{sections.algorithmDesign}</Text>
        </View>

        {/* Section 6: Human Oversight */}
        <SectionWithRequirements
          title="6. Human Oversight Measures"
          text={sections.humanOversight.text}
          requirements={sections.humanOversight.requirements}
        />

        {/* Section 7: Accuracy and Robustness */}
        <SectionWithRequirements
          title="7. Accuracy and Robustness"
          text={sections.accuracyRobustness.text}
          requirements={sections.accuracyRobustness.requirements}
        />

        {/* Section 8: Logging */}
        <SectionWithRequirements
          title="8. Logging Capabilities"
          text={sections.logging.text}
          requirements={sections.logging.requirements}
        />
      </Page>

      {/* Evidence Appendix */}
      <Page size="A4" style={styles.page}>
        <PageHeader title="EU AI Act - Technical Documentation" branding={effectiveBranding} />

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Appendix: Evidence Index</Text>
          <View style={styles.table}>
            <View style={[styles.tableRow, styles.tableHeader]}>
              <Text style={styles.colFile}>File Name</Text>
              <Text style={styles.colSha}>SHA-256</Text>
              <Text style={styles.colControl}>Control</Text>
              <Text style={styles.colDate}>Uploaded</Text>
            </View>
            {evidenceIndex.map((e, i) => (
              <View key={i} style={styles.tableRow}>
                <Text style={styles.colFile}>{e.fileName}</Text>
                <Text style={styles.colSha}>{e.sha256}</Text>
                <Text style={styles.colControl}>{e.controlCode}</Text>
                <Text style={styles.colDate}>{e.uploadedAt}</Text>
              </View>
            ))}
          </View>
        </View>

        <PageFooter branding={effectiveBranding} generatedAt={generatedAt} />
      </Page>
    </Document>
  );
}
