import { Document, Page, View, Text, StyleSheet } from "@react-pdf/renderer";
import { ScoreDonut } from "./components/ScoreDonut.js";
import type { AssessmentResult } from "../types.js";

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: "Helvetica", fontSize: 10 },
  title: { fontSize: 24, fontWeight: "bold", marginBottom: 4, color: "#111827" },
  subtitle: { fontSize: 12, color: "#6b7280", marginBottom: 24 },
  section: { marginBottom: 20 },
  sectionTitle: { fontSize: 16, fontWeight: "bold", marginBottom: 10, color: "#1f2937" },
  frameworkRow: { flexDirection: "row", alignItems: "center", gap: 12, marginBottom: 12, padding: 10, backgroundColor: "#f9fafb", borderRadius: 4 },
  frameworkName: { fontSize: 11, fontWeight: "bold", color: "#1f2937" },
  frameworkVerdict: { fontSize: 10, color: "#6b7280" },
  footer: { position: "absolute", bottom: 30, left: 40, right: 40, textAlign: "center", fontSize: 8, color: "#9ca3af" },
});

export interface ExecutiveReportData {
  orgName: string;
  assessments: Array<{ frameworkName: string; assessment: AssessmentResult }>;
  generatedAt: string;
}

export function ExecutiveReport({ data }: { data: ExecutiveReportData }) {
  const { orgName, assessments, generatedAt } = data;
  const criticalCount = assessments.filter((a) => a.assessment.verdict === "non_compliant").length;

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>Executive Compliance Report</Text>
        <Text style={styles.subtitle}>{orgName} — Risk Posture Overview</Text>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Framework Compliance Status</Text>
          {assessments.map((entry) => (
            <View key={entry.frameworkName} style={styles.frameworkRow}>
              <ScoreDonut score={entry.assessment.score} size={50} />
              <View>
                <Text style={styles.frameworkName}>{entry.frameworkName}</Text>
                <Text style={styles.frameworkVerdict}>
                  {entry.assessment.verdict.replace(/_/g, " ")} — {Math.round(entry.assessment.score * 100)}%
                </Text>
              </View>
            </View>
          ))}
        </View>

        {criticalCount > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Remediation Priority</Text>
            <Text>{criticalCount} framework(s) require immediate attention.</Text>
          </View>
        )}

        <Text style={styles.footer}>Generated by SENTINEL on {generatedAt} | Confidential</Text>
      </Page>
    </Document>
  );
}
