import { Document, Page, View, Text, StyleSheet } from "@react-pdf/renderer";
import { ScoreDonut } from "./components/ScoreDonut.js";
import { PageHeader } from "./components/PageHeader.js";
import { PageFooter } from "./components/PageFooter.js";
import type { BrandingContext } from "./branding.js";
import type { AssessmentResult } from "../types.js";

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: "Helvetica", fontSize: 10 },
  section: { marginBottom: 20 },
  sectionTitle: { fontSize: 16, fontWeight: "bold", marginBottom: 10, color: "#1f2937" },
  frameworkRow: { flexDirection: "row", alignItems: "center", gap: 12, marginBottom: 12, padding: 10, backgroundColor: "#f9fafb", borderRadius: 4 },
  frameworkName: { fontSize: 11, fontWeight: "bold", color: "#1f2937" },
  frameworkVerdict: { fontSize: 10, color: "#6b7280" },
});

export interface ExecutiveReportData {
  orgName: string;
  assessments: Array<{ frameworkName: string; assessment: AssessmentResult }>;
  generatedAt: string;
}

export function ExecutiveReport({ data, branding }: { data: ExecutiveReportData; branding?: BrandingContext }) {
  const { orgName, assessments, generatedAt } = data;
  const effectiveBranding: BrandingContext = branding ?? { orgName, accentColor: "#2563EB", footerText: "Generated by SENTINEL", confidentialityBanner: "CONFIDENTIAL" };
  const criticalCount = assessments.filter((a) => a.assessment.verdict === "non_compliant").length;

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <PageHeader title="Executive Compliance Report" branding={effectiveBranding} />

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Framework Compliance Status</Text>
          {assessments.map((entry) => (
            <View key={entry.frameworkName} style={styles.frameworkRow}>
              <ScoreDonut score={entry.assessment.score} size={50} />
              <View>
                <Text style={styles.frameworkName}>{entry.frameworkName}</Text>
                <Text style={styles.frameworkVerdict}>
                  {entry.assessment.verdict.replace(/_/g, " ")} — {Math.round(entry.assessment.score * 100)}%
                </Text>
              </View>
            </View>
          ))}
        </View>

        {criticalCount > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Remediation Priority</Text>
            <Text>{criticalCount} framework(s) require immediate attention.</Text>
          </View>
        )}

        <PageFooter branding={effectiveBranding} generatedAt={generatedAt} />
      </Page>
    </Document>
  );
}
