import type { WizardControlMeta } from "./types.js";

export const EU_AI_ACT_CONTROLS: WizardControlMeta[] = [
  // Phase 1 — no dependencies
  {
    code: "AIA-9",
    article: "Art. 9",
    title: "Risk Management System",
    phase: 1,
    dependencies: [],
    requirements: [
      { key: "risk_identified", label: "Risks to health, safety, fundamental rights identified", completed: false, optional: false },
      { key: "risk_mitigated", label: "Risk mitigation measures documented", completed: false, optional: false },
      { key: "risk_residual", label: "Residual risk assessment performed", completed: false, optional: false },
      { key: "risk_testing", label: "Testing procedures defined for risk measures", completed: false, optional: false },
      { key: "risk_lifecycle", label: "Risk management covers entire lifecycle", completed: false, optional: false },
    ],
    documentContributions: ["technical_documentation", "instructions_for_use"],
    skipUnlocksDependents: false,
  },
  {
    code: "AIA-10",
    article: "Art. 10",
    title: "Data & Data Governance",
    phase: 1,
    dependencies: [],
    requirements: [
      { key: "data_quality", label: "Data quality criteria defined and measured", completed: false, optional: false },
      { key: "data_relevance", label: "Training data relevance and representativeness assessed", completed: false, optional: false },
      { key: "data_bias", label: "Bias examination and mitigation documented", completed: false, optional: false },
      { key: "data_gaps", label: "Data gaps identified and addressed", completed: false, optional: false },
      { key: "data_governance", label: "Data governance procedures established", completed: false, optional: false },
      { key: "data_privacy", label: "Personal data processing compliance verified", completed: false, optional: true },
    ],
    documentContributions: ["technical_documentation", "instructions_for_use"],
    skipUnlocksDependents: false,
  },
  {
    code: "AIA-12",
    article: "Art. 12",
    title: "Record-Keeping (Logging)",
    phase: 1,
    dependencies: [],
    requirements: [
      { key: "log_events", label: "Logged events and data points specified", completed: false, optional: false },
      { key: "log_retention", label: "Log retention periods defined", completed: false, optional: false },
      { key: "log_traceability", label: "Traceability of AI system decisions enabled", completed: false, optional: false },
    ],
    documentContributions: ["technical_documentation"],
    skipUnlocksDependents: true,
  },
  // Phase 2 — depends on phase 1 controls
  {
    code: "AIA-11",
    article: "Art. 11",
    title: "Technical Documentation",
    phase: 2,
    dependencies: ["AIA-9", "AIA-10"],
    requirements: [
      { key: "tech_doc_system", label: "General description of the AI system documented", completed: false, optional: false },
      { key: "tech_doc_design", label: "Design specifications and development process described", completed: false, optional: false },
      { key: "tech_doc_monitoring", label: "Monitoring and functioning information provided", completed: false, optional: false },
      { key: "tech_doc_validation", label: "Validation and testing procedures documented", completed: false, optional: false },
    ],
    documentContributions: ["technical_documentation"],
    skipUnlocksDependents: false,
  },
  {
    code: "AIA-13",
    article: "Art. 13",
    title: "Transparency & User Info",
    phase: 2,
    dependencies: ["AIA-9"],
    requirements: [
      { key: "transparency_purpose", label: "Intended purpose clearly communicated", completed: false, optional: false },
      { key: "transparency_limitations", label: "Known limitations and risks disclosed", completed: false, optional: false },
      { key: "transparency_accuracy", label: "Accuracy levels and expected errors documented", completed: false, optional: false },
      { key: "transparency_human", label: "Human oversight measures described to users", completed: false, optional: false },
    ],
    documentContributions: ["instructions_for_use"],
    skipUnlocksDependents: true,
  },
  {
    code: "AIA-14",
    article: "Art. 14",
    title: "Human Oversight",
    phase: 2,
    dependencies: ["AIA-9"],
    requirements: [
      { key: "oversight_design", label: "Human oversight built into system design", completed: false, optional: false },
      { key: "oversight_interface", label: "Interface enables effective oversight by natural persons", completed: false, optional: false },
      { key: "oversight_override", label: "Override and intervention mechanisms available", completed: false, optional: false },
      { key: "oversight_stop", label: "Ability to stop or reverse system outputs", completed: false, optional: false },
      { key: "oversight_training", label: "Oversight personnel adequately trained", completed: false, optional: true },
    ],
    documentContributions: ["technical_documentation", "instructions_for_use"],
    skipUnlocksDependents: true,
  },
  {
    code: "AIA-15",
    article: "Art. 15",
    title: "Accuracy, Robustness & Cybersecurity",
    phase: 2,
    dependencies: ["AIA-9", "AIA-10"],
    requirements: [
      { key: "accuracy_levels", label: "Accuracy levels declared and measured", completed: false, optional: false },
      { key: "accuracy_metrics", label: "Accuracy metrics appropriate for intended purpose", completed: false, optional: false },
      { key: "robustness_errors", label: "Resilience to errors and faults demonstrated", completed: false, optional: false },
      { key: "robustness_adversarial", label: "Robustness against adversarial attacks assessed", completed: false, optional: false },
      { key: "cyber_measures", label: "Cybersecurity measures implemented", completed: false, optional: false },
      { key: "cyber_integrity", label: "Data and model integrity protections in place", completed: false, optional: false },
    ],
    documentContributions: ["technical_documentation", "instructions_for_use"],
    skipUnlocksDependents: false,
  },
  // Phase 3
  {
    code: "AIA-17",
    article: "Art. 17",
    title: "Quality Management System",
    phase: 3,
    dependencies: ["AIA-11", "AIA-15"],
    requirements: [
      { key: "qms_strategy", label: "Quality management strategy documented", completed: false, optional: false },
      { key: "qms_design", label: "Design and development quality controls defined", completed: false, optional: false },
      { key: "qms_testing", label: "Testing and validation procedures established", completed: false, optional: false },
      { key: "qms_standards", label: "Applicable standards and specifications identified", completed: false, optional: false },
      { key: "qms_resources", label: "Resource management and responsibilities assigned", completed: false, optional: false },
    ],
    documentContributions: ["post_market_monitoring"],
    skipUnlocksDependents: false,
  },
  {
    code: "AIA-26",
    article: "Art. 26",
    title: "Obligations of Deployers",
    phase: 3,
    dependencies: ["AIA-13", "AIA-14"],
    requirements: [
      { key: "deployer_use", label: "Use in accordance with instructions verified", completed: false, optional: false },
      { key: "deployer_oversight", label: "Human oversight persons assigned and capable", completed: false, optional: false },
      { key: "deployer_monitoring", label: "Input data relevance monitored", completed: false, optional: false },
      { key: "deployer_inform", label: "Individuals informed of AI system use", completed: false, optional: false },
    ],
    documentContributions: ["instructions_for_use"],
    skipUnlocksDependents: true,
  },
  {
    code: "AIA-47",
    article: "Art. 47",
    title: "EU Declaration of Conformity",
    phase: 3,
    dependencies: ["AIA-11", "AIA-17"],
    requirements: [
      { key: "doc_identifier", label: "Unique declaration identifier assigned", completed: false, optional: false },
      { key: "doc_conformity", label: "Conformity assessment procedure completed", completed: false, optional: false },
      { key: "doc_standards", label: "Applied standards and specifications referenced", completed: false, optional: false },
    ],
    documentContributions: ["declaration_of_conformity"],
    skipUnlocksDependents: false,
  },
  // Phase 4
  {
    code: "AIA-60",
    article: "Art. 60",
    title: "Serious Incident Reporting",
    phase: 4,
    dependencies: ["AIA-17", "AIA-26"],
    requirements: [
      { key: "incident_process", label: "Incident reporting process defined", completed: false, optional: false },
      { key: "incident_timelines", label: "Notification timelines established", completed: false, optional: false },
      { key: "incident_authority", label: "Relevant market surveillance authority identified", completed: false, optional: false },
      { key: "incident_corrective", label: "Corrective action procedures documented", completed: false, optional: false },
    ],
    documentContributions: ["post_market_monitoring"],
    skipUnlocksDependents: false,
  },
  {
    code: "AIA-61",
    article: "Art. 61",
    title: "Post-Market Monitoring",
    phase: 4,
    dependencies: ["AIA-17", "AIA-60"],
    requirements: [
      { key: "pms_plan", label: "Post-market monitoring plan established", completed: false, optional: false },
      { key: "pms_data", label: "Relevant data collection procedures defined", completed: false, optional: false },
      { key: "pms_analysis", label: "Data analysis and evaluation methods documented", completed: false, optional: false },
      { key: "pms_update", label: "System update procedures based on monitoring defined", completed: false, optional: false },
      { key: "pms_reporting", label: "Regular reporting cadence established", completed: false, optional: false },
    ],
    documentContributions: ["post_market_monitoring"],
    skipUnlocksDependents: false,
  },
];

export const EU_AI_ACT_CONTROL_MAP = new Map(
  EU_AI_ACT_CONTROLS.map((c) => [c.code, c]),
);
