"""AI-Generation Detector Agent.

Combines stylometric analysis, tool marker detection, and git timing heuristics
to estimate the probability that code was generated by AI tools.
"""

from __future__ import annotations

from sentinel_agents.base import BaseAgent
from sentinel_agents.types import Confidence, DiffEvent, DiffFile, Finding, Severity

from sentinel_aidetector.markers import detect_markers
from sentinel_aidetector.stylometric import analyze_entropy, analyze_naming_uniformity
from sentinel_aidetector.timing import analyze_timing

# Weight each signal when combining into a final probability
_WEIGHT_ENTROPY = 0.25
_WEIGHT_UNIFORMITY = 0.20
_WEIGHT_MARKERS = 0.35
_WEIGHT_TIMING = 0.20

# Entropy thresholds for probability mapping
_ENTROPY_LOW = 3.0  # Below this -> high probability of AI
_ENTROPY_HIGH = 6.0  # Above this -> low probability of AI


def _entropy_to_probability(entropy: float, token_count: int) -> float:
    """Convert entropy to an AI-generation probability.

    Lower entropy means more predictable token usage, suggesting AI generation.
    """
    if token_count == 0:
        return 0.0  # No tokens, no signal
    if entropy <= 0.0:
        return 0.9  # All identical tokens — strong AI signal
    if entropy <= _ENTROPY_LOW:
        return 1.0
    if entropy >= _ENTROPY_HIGH:
        return 0.0
    return 1.0 - (entropy - _ENTROPY_LOW) / (_ENTROPY_HIGH - _ENTROPY_LOW)


def _file_code(diff_file: DiffFile) -> str:
    """Extract the added code from a DiffFile's hunks."""
    lines: list[str] = []
    for hunk in diff_file.hunks:
        for line in hunk.content.split("\n"):
            if line.startswith("+") and not line.startswith("+++"):
                lines.append(line[1:])  # Strip the leading '+'
    return "\n".join(lines)


def _confidence_from_probability(prob: float) -> Confidence:
    if prob >= 0.75:
        return Confidence.HIGH
    if prob >= 0.45:
        return Confidence.MEDIUM
    return Confidence.LOW


def _severity_from_probability(prob: float) -> Severity:
    if prob >= 0.80:
        return Severity.HIGH
    if prob >= 0.50:
        return Severity.MEDIUM
    return Severity.LOW


class AIDetectorAgent(BaseAgent):
    name = "ai-detector"
    version = "0.1.0"
    ruleset_version = "rules-2026.03.09-a"
    ruleset_hash = "sha256:aidetect-v1"

    def process(self, event: DiffEvent) -> list[Finding]:
        findings: list[Finding] = []
        timing_signal = analyze_timing(event.files, event.timestamp)

        for diff_file in event.files:
            code = _file_code(diff_file)
            if not code.strip():
                continue

            # Stylometric signals
            entropy = analyze_entropy(code)
            token_count = len(code.split())
            entropy_prob = _entropy_to_probability(entropy, token_count)
            uniformity = analyze_naming_uniformity(code)

            # Marker detection
            marker_matches = detect_markers(code)
            marker_prob = min(1.0, len(marker_matches) * 0.4)

            # Combine signals with weights
            probability = (
                _WEIGHT_ENTROPY * entropy_prob
                + _WEIGHT_UNIFORMITY * uniformity
                + _WEIGHT_MARKERS * marker_prob
                + _WEIGHT_TIMING * timing_signal.probability
            )
            probability = max(0.0, min(1.0, probability))

            # Only report if probability is meaningful
            if probability < 0.15:
                continue

            first_line = 1
            last_line = 1
            if diff_file.hunks:
                first_line = diff_file.hunks[0].new_start
                last_hunk = diff_file.hunks[-1]
                last_line = last_hunk.new_start + last_hunk.new_count

            marker_tools = sorted({m.tool for m in marker_matches})
            description_parts = [
                f"AI-generation probability: {probability:.0%}.",
                f"Entropy: {entropy:.2f}, Uniformity: {uniformity:.2f}.",
            ]
            if marker_tools:
                description_parts.append(f"Tool markers detected: {', '.join(marker_tools)}.")
            if timing_signal.probability > 0:
                description_parts.append(
                    f"Bulk commit signal: {timing_signal.lines_changed} lines added."
                )

            findings.append(
                Finding(
                    type="ai-detection",
                    file=diff_file.path,
                    line_start=first_line,
                    line_end=last_line,
                    severity=_severity_from_probability(probability),
                    confidence=_confidence_from_probability(probability),
                    title=f"Possible AI-generated code ({probability:.0%})",
                    description=" ".join(description_parts),
                    remediation="Review code for correctness, security, and adherence to project "
                    "standards. Ensure AI-generated code has been manually verified.",
                    category="ai-generated",
                    scanner="ai-detector",
                    extra={
                        "ai_probability": round(probability, 3),
                        "entropy": round(entropy, 3),
                        "naming_uniformity": round(uniformity, 3),
                        "marker_count": len(marker_matches),
                        "marker_tools": marker_tools,
                        "lines_changed": timing_signal.lines_changed,
                    },
                )
            )

        return findings
