"""AI-Generation Detector Agent.

Combines stylometric analysis, tool marker detection, and git timing heuristics
to estimate the probability that code was generated by AI tools.

Uses adaptive confidence calibration via agent_core when available.
"""

from __future__ import annotations

from typing import Any

from sentinel_agents.base import BaseAgent
from sentinel_agents.types import Confidence, DiffEvent, DiffFile, Finding, Severity

from sentinel_aidetector.compliance_checks import (
    check_bias_indicators,
    check_model_provenance,
    check_oversight_gaps,
)
from sentinel_aidetector.markers import detect_markers
from sentinel_aidetector.stylometric import (
    analyze_ast_entropy,
    analyze_entropy,
    analyze_naming_uniformity,
)
from sentinel_aidetector.timing import analyze_timing
from sentinel_aidetector.trace import SignalDetail, TraceBuilder

# Default weights (used when no calibrator is available)
_WEIGHT_ENTROPY = 0.25
_WEIGHT_UNIFORMITY = 0.20
_WEIGHT_MARKERS = 0.35
_WEIGHT_TIMING = 0.20

# Entropy thresholds for probability mapping
_ENTROPY_LOW = 3.0  # Below this -> high probability of AI
_ENTROPY_HIGH = 6.0  # Above this -> low probability of AI


def _entropy_to_probability(entropy: float, token_count: int) -> float:
    """Convert entropy to an AI-generation probability."""
    if token_count == 0:
        return 0.0
    if entropy <= 0.0:
        return 0.9
    if entropy <= _ENTROPY_LOW:
        return 1.0
    if entropy >= _ENTROPY_HIGH:
        return 0.0
    return 1.0 - (entropy - _ENTROPY_LOW) / (_ENTROPY_HIGH - _ENTROPY_LOW)


def _file_code(diff_file: DiffFile) -> str:
    """Extract the added code from a DiffFile's hunks."""
    lines: list[str] = []
    for hunk in diff_file.hunks:
        for line in hunk.content.split("\n"):
            if line.startswith("+") and not line.startswith("+++"):
                lines.append(line[1:])
    return "\n".join(lines)


def _confidence_from_probability(prob: float) -> Confidence:
    if prob >= 0.75:
        return Confidence.HIGH
    if prob >= 0.45:
        return Confidence.MEDIUM
    return Confidence.LOW


def _severity_from_probability(prob: float) -> Severity:
    if prob >= 0.80:
        return Severity.HIGH
    if prob >= 0.50:
        return Severity.MEDIUM
    return Severity.LOW


class AIDetectorAgent(BaseAgent):
    name = "ai-detector"
    version = "0.2.0"
    ruleset_version = "rules-2026.03.11-a"
    ruleset_hash = "sha256:aidetect-v2"

    def __init__(self, calibrator: Any = None) -> None:
        """Initialize with optional ConfidenceCalibrator for adaptive weights."""
        self._calibrator = calibrator

    def process(self, event: DiffEvent) -> list[Finding]:
        findings: list[Finding] = []
        timing_signal = analyze_timing(event.files, event.timestamp)

        for diff_file in event.files:
            code = _file_code(diff_file)
            if not code.strip():
                continue

            lang = diff_file.language.lower()

            # AST-aware entropy when language is supported
            ast_entropy = analyze_ast_entropy(code, lang)
            entropy = ast_entropy.combined
            token_count = len(code.split())
            entropy_prob = _entropy_to_probability(entropy, token_count)
            uniformity = analyze_naming_uniformity(code)

            # Marker detection with language-aware AST extraction
            marker_matches = detect_markers(code, lang)
            marker_prob = min(1.0, len(marker_matches) * 0.4)

            # Combine signals with weights
            probability = (
                _WEIGHT_ENTROPY * entropy_prob
                + _WEIGHT_UNIFORMITY * uniformity
                + _WEIGHT_MARKERS * marker_prob
                + _WEIGHT_TIMING * timing_signal.probability
            )
            probability = max(0.0, min(1.0, probability))

            if probability < 0.15:
                continue

            first_line = 1
            last_line = 1
            if diff_file.hunks:
                first_line = diff_file.hunks[0].new_start
                last_hunk = diff_file.hunks[-1]
                last_line = last_hunk.new_start + last_hunk.new_count

            marker_tools = sorted({m.tool for m in marker_matches})
            description_parts = [
                f"AI-generation probability: {probability:.0%}.",
                f"Entropy: {entropy:.2f} (token={ast_entropy.token_entropy:.2f}, "
                f"struct={ast_entropy.structure_entropy:.2f}, "
                f"naming={ast_entropy.naming_entropy:.2f}).",
                f"Uniformity: {uniformity:.2f}.",
            ]
            if marker_tools:
                description_parts.append(f"Tool markers detected: {', '.join(marker_tools)}.")
            if timing_signal.probability > 0:
                description_parts.append(
                    f"Bulk commit signal: {timing_signal.lines_changed} lines added"
                    f" across {timing_signal.file_count} files."
                )
                if timing_signal.is_burst:
                    description_parts.append("Burst pattern detected.")

            finding = Finding(
                type="ai-detection",
                file=diff_file.path,
                line_start=first_line,
                line_end=last_line,
                severity=_severity_from_probability(probability),
                confidence=_confidence_from_probability(probability),
                title=f"Possible AI-generated code ({probability:.0%})",
                description=" ".join(description_parts),
                remediation="Review code for correctness, security, and adherence to project "
                "standards. Ensure AI-generated code has been manually verified.",
                category="ai-generated",
                scanner="ai-detector",
                extra=TraceBuilder(
                    tool_name=marker_tools[0] if marker_tools else None,
                    entropy=SignalDetail(
                        weight=_WEIGHT_ENTROPY,
                        raw_value=round(entropy, 3),
                        probability=round(entropy_prob, 3),
                        contribution=round(_WEIGHT_ENTROPY * entropy_prob, 4),
                        detail={
                            "tokenEntropy": round(ast_entropy.token_entropy, 3),
                            "structureEntropy": round(ast_entropy.structure_entropy, 3),
                            "namingEntropy": round(ast_entropy.naming_entropy, 3),
                        },
                    ),
                    uniformity=SignalDetail(
                        weight=_WEIGHT_UNIFORMITY,
                        raw_value=round(uniformity, 3),
                        probability=round(uniformity, 3),
                        contribution=round(_WEIGHT_UNIFORMITY * uniformity, 4),
                    ),
                    markers=SignalDetail(
                        weight=_WEIGHT_MARKERS,
                        raw_value=len(marker_matches),
                        probability=round(marker_prob, 3),
                        contribution=round(_WEIGHT_MARKERS * marker_prob, 4),
                        detail={
                            "tools": marker_tools,
                            "matchCount": len(marker_matches),
                        },
                    ),
                    timing=SignalDetail(
                        weight=_WEIGHT_TIMING,
                        raw_value=timing_signal.lines_changed,
                        probability=round(timing_signal.probability, 3),
                        contribution=round(_WEIGHT_TIMING * timing_signal.probability, 4),
                        detail={
                            "linesChanged": timing_signal.lines_changed,
                            "isBurst": timing_signal.is_burst,
                            "sizeUniformity": round(timing_signal.size_uniformity, 3),
                        },
                    ),
                ).to_extra(),
            )

            # Apply adaptive calibration if available
            if self._calibrator:
                finding_dict = {
                    "confidence": finding.confidence.value,
                    "category": finding.category,
                }
                calibrated = self._calibrator.calibrate(finding_dict, self.name)
                try:
                    finding.confidence = Confidence(calibrated["confidence"])
                except (ValueError, KeyError):
                    pass

            findings.append(finding)

        # NIST/HIPAA compliance checks
        findings.extend(check_model_provenance(event.files))
        findings.extend(check_bias_indicators(event.files))
        findings.extend(check_oversight_gaps(event.files))

        return findings
