"""AI tool marker detection.

Scans code content for comments, metadata, and patterns that indicate AI tool usage
(Copilot, Cursor, Claude, ChatGPT, etc.).
"""

from __future__ import annotations

import re
from dataclasses import dataclass


@dataclass
class MarkerMatch:
    """A detected AI tool marker in code."""

    tool: str
    pattern: str
    line_number: int
    line_content: str


# Each tuple: (tool_name, compiled_regex)
_MARKER_PATTERNS: list[tuple[str, re.Pattern[str]]] = [
    # Generic "Generated by" markers
    ("ai-generic", re.compile(r"(?i)generated\s+by\s+(ai|copilot|cursor|claude|chatgpt|gpt)")),
    ("ai-generic", re.compile(r"(?i)auto[- ]?generated\s+(by\s+)?(ai|llm|assistant)")),
    ("ai-generic", re.compile(r"(?i)created\s+with\s+(ai|copilot|cursor|claude|chatgpt|gpt)")),
    # GitHub Copilot
    ("copilot", re.compile(r"(?i)github\s+copilot")),
    ("copilot", re.compile(r"(?i)(#|//|/\*|\*)\s*.*\bcopilot\b")),
    # Cursor
    ("cursor", re.compile(r"@cursor")),
    ("cursor", re.compile(r"(?i)\bcursor\s+(ai|ide|editor)\b")),
    # Claude / Anthropic
    ("claude", re.compile(r"(?i)\bclaude\b.*\b(generated|wrote|created|authored)\b")),
    ("claude", re.compile(r"(?i)\b(generated|wrote|created|authored)\b.*\bclaude\b")),
    ("claude", re.compile(r"(?i)(#|//|/\*|\*)\s*.*\banthrop(ic|ics?)\b")),
    # ChatGPT / OpenAI
    ("chatgpt", re.compile(r"(?i)\bchatgpt\b")),
    ("chatgpt", re.compile(r"(?i)\bopenai\b.*\b(generated|wrote|created)\b")),
    ("chatgpt", re.compile(r"(?i)\b(generated|wrote|created)\b.*\bopenai\b")),
    ("chatgpt", re.compile(r"(?i)\bgpt-[34]\b")),
    # AI assistant generic patterns
    ("ai-generic", re.compile(r"(?i)\bai[- ]assisted\b")),
    ("ai-generic", re.compile(r"(?i)\bllm[- ](generated|output|written)\b")),
    # Code-specific AI patterns (common in AI boilerplate)
    ("ai-generic", re.compile(r"(?i)#\s*TODO:\s*review\s+ai[- ]generated")),
]


def detect_markers(content: str) -> list[MarkerMatch]:
    """Scan content for AI tool markers.

    Returns a list of MarkerMatch instances for every pattern match found.
    """
    matches: list[MarkerMatch] = []
    lines = content.split("\n")

    for line_idx, line in enumerate(lines):
        for tool, pattern in _MARKER_PATTERNS:
            if pattern.search(line):
                matches.append(
                    MarkerMatch(
                        tool=tool,
                        pattern=pattern.pattern,
                        line_number=line_idx + 1,
                        line_content=line.strip(),
                    )
                )

    return matches
