/**
 * USAGE RESTRICTION: Only import this file from:
 *   - __tests__/ directories (unit/integration tests)
 *   - lib/demo-data.ts (demo environment only, behind DEMO_MODE=true)
 * Never import directly in page components or lib/api.ts.
 */

import type { RemediationItem, RemediationStats } from "./types";

export const MOCK_STATS: RemediationStats = {
  open: 12,
  inProgress: 8,
  overdue: 3,
  completed: 45,
  acceptedRisk: 2,
  avgResolutionDays: 4,
  slaCompliance: 87,
};

export const MOCK_ITEMS: RemediationItem[] = [
  {
    id: "rem-1",
    orgId: "org-1",
    frameworkSlug: "hipaa",
    controlCode: "TS-1.4",
    title: "Implement encryption at rest for PHI data stores",
    description:
      "HIPAA Technical Safeguard TS-1.4 requires encryption at rest for all data stores containing PHI.",
    status: "in_progress",
    priority: "critical",
    assignedTo: "security-team",
    dueDate: new Date(Date.now() + 7 * 86400000).toISOString(),
    completedAt: null,
    completedBy: null,
    evidenceNotes: null,
    linkedFindingIds: ["f-1", "f-2"],
    createdBy: "admin",
    createdAt: new Date(Date.now() - 14 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    parentId: null,
    findingId: null,
    itemType: "compliance",
    priorityScore: 82,
    externalRef: "jira:SEC-234",
    children: [
      {
        id: "rem-1a",
        orgId: "org-1",
        frameworkSlug: null,
        controlCode: null,
        title: "Upgrade PostgreSQL encryption module",
        description: "Enable pgcrypto extension and encrypt PHI columns",
        status: "completed",
        priority: "high",
        assignedTo: "db-team",
        dueDate: new Date(Date.now() - 3 * 86400000).toISOString(),
        completedAt: new Date(Date.now() - 4 * 86400000).toISOString(),
        completedBy: "db-engineer",
        evidenceNotes: "pgcrypto enabled, all PHI columns encrypted",
        linkedFindingIds: ["f-1"],
        createdBy: "admin",
        createdAt: new Date(Date.now() - 12 * 86400000).toISOString(),
        updatedAt: new Date(Date.now() - 4 * 86400000).toISOString(),
        parentId: "rem-1",
        findingId: "f-1",
        itemType: "finding",
        priorityScore: 30,
        externalRef: null,
      },
    ],
  },
  {
    id: "rem-2",
    orgId: "org-1",
    frameworkSlug: "soc2",
    controlCode: "CC6.1",
    title: "Implement network access controls",
    description:
      "SOC 2 CC6.1 requires logical access controls for network resources.",
    status: "open",
    priority: "high",
    assignedTo: null,
    dueDate: new Date(Date.now() + 14 * 86400000).toISOString(),
    completedAt: null,
    completedBy: null,
    evidenceNotes: null,
    linkedFindingIds: [],
    createdBy: "admin",
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    parentId: null,
    findingId: null,
    itemType: "compliance",
    priorityScore: 55,
    externalRef: null,
    children: [],
  },
  {
    id: "rem-3",
    orgId: "org-1",
    frameworkSlug: null,
    controlCode: null,
    title: "Fix CVE-2024-38816 in Spring Framework",
    description:
      "Path traversal vulnerability in Spring Framework allows unauthorized file access.",
    status: "open",
    priority: "critical",
    assignedTo: "dev-team",
    dueDate: new Date(Date.now() - 2 * 86400000).toISOString(),
    completedAt: null,
    completedBy: null,
    evidenceNotes: null,
    linkedFindingIds: ["f-3"],
    createdBy: "scanner",
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    parentId: null,
    findingId: "f-3",
    itemType: "finding",
    priorityScore: 96,
    externalRef: null,
    children: [],
  },
];
